# Generated by Django 2.1.15 on 2020-06-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20200613_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='runningTime',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
