# Generated by Django 2.1.15 on 2020-06-13 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20200613_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='poster1',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='poster2',
            new_name='image2',
        ),
    ]
