# Generated by Django 2.1.15 on 2020-06-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20200613_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='pubDate',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='movie',
            name='userRating',
            field=models.CharField(default='', max_length=10),
        ),
    ]
