# Generated by Django 2.1.15 on 2020-06-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20200613_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='runningTime',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
