# Generated by Django 2.1.15 on 2020-06-14 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20200613_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='plot',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
